def get_file_icon(filename: str, is_dir: bool) -> str:
    if is_dir:
        return "📁"

    ext = filename.lower().split('.')[-1] if '.' in filename else ''
    icon_map = {
        'py': '🐍',
        'js': '📜',
        'ts': '📘',
        'java': '☕',
        'c': '©️',
        'cpp': '©️',
        'h': '📋',
        'html': '🌐',
        'css': '🎨',
        'json': '📊',
        'xml': '📄',
        'md': '📝',
        'txt': '📄',
        'pdf': '📕',
        'doc': '📘',
        'docx': '📘',
        'xls': '📗',
        'xlsx': '📗',
        'ppt': '📙',
        'pptx': '📙',
        'zip': '📦',
        'rar': '📦',
        '7z': '📦',
        'tar': '📦',
        'gz': '📦',
        'jpg': '🖼️',
        'jpeg': '🖼️',
        'png': '🖼️',
        'gif': '🖼️',
        'svg': '🖼️',
        'bmp': '🖼️',
        'ico': '🖼️',
        'mp3': '🎵',
        'wav': '🎵',
        'flac': '🎵',
        'mp4': '🎬',
        'avi': '🎬',
        'mkv': '🎬',
        'mov': '🎬',
        'sh': '⚙️',
        'bat': '⚙️',
        'exe': '⚙️',
        'dll': '⚙️',
        'so': '⚙️',
        'db': '🗄️',
        'sql': '🗄️',
        'log': '📋',
        'ini': '⚙️',
        'cfg': '⚙️',
        'conf': '⚙️',
        'yml': '⚙️',
        'yaml': '⚙️',
        'lock': '🔒',
        'key': '🔑',
        'pem': '🔑',
        'crt': '🔑',
        'git': '📂',
    }

    return icon_map.get(ext, '📄')
